<a href="https://colab.research.google.com/github/JaymersonFerreira/RESILIA/blob/main/DataFrame_Series_e_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = orange>ARRAYS

- Array em Python são um estrutura de dados que permite armazenar e manipular coleções de elementos do mesmo tipo. Elas são úteis para trabalhar com matrizes, vetores e sequencias númericas, entre outros.
- Em python, Existem várias bibliotecas que oferecem suporte a Array, como Numpy e Array. A biclioteca Numpy é amplamente utilizada para a manipulação de dados numéricos.

- Para criar um Arrayem NumPy, você pode usar a função array(), passando uma lista ou tupla de elementos como argumento:

In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


- Nesse exemplo, a variável ***a*** é um Array NumPy com elementos 1,2,3,4 e 5. Você pode acesar os elementos do Array usnado a notação de colchetes,
coo em a[0], para acessar o primeiro elemento.

- NumPy também oferece muitas funções para criar Arrays preenchidos com valores padrão, com zeros(), ones(), full() e arange(). Por exemplo, para criar um Array de zeros com 5 elementos, você usar o seguinte código:


In [ ]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [ ]:
c = np.ones(3)
print(c)

[1. 1. 1.]


In [ ]:
d = np.arange(6)
print(d)

[0 1 2 3 4 5]


- Para criar um Array com valores sequeciais, você pode usar função arange, como em np.arange(0, 10, 2) para criar array com valores de 0 a 10 (excluiva) com um intervalo de 2.


In [ ]:
e = np.arange(0,10,2)
print(e)

[0 2 4 6 8]


- Além disso, NumPy oferece muitas funções para manipular e processar Arrays, como sum(), mean(),std(), max() e min(). Essas Funções permite realizar operações matemáticas em Array e obter estatísticas sobre seus valores.
- Por exemplo, para calcular a média dos valores de um Array, você pode usar função mean(), como em np.mean(a).Para obter o valor máximo de array, você pode usar a função max(), como em np.max(a)

In [8]:
np.max(a)

5

- Numpy tabém oferece muitas funcionalidade para operações de álgebra linear,como multiplicadores de matrizes, inversão de matrizes e decomposição de valores singulares.
- Como vimos, essa são apenas alguma das funcionalidades oferecidas pelo numpy para trabalhar com Array em Python. A biclioteca utilizada em ciência de dados, processamento de imagens, aprendizado de máquina e ooutra área que exigem manipulação de dados numéricos. Vamos dar uma olhada em outra estrutura fundamental para nossos estudos: Series!


# <font color = orange>Series

- Series em Python é um estrutura de dados que permite armazenar e manipular coleções de dados inidimencionais e rotulados. Ela é útil para trabalhar com dados de séries temporais, dados financeiros, dados de ações, entre outros.
- Em Python, a biclioteca Pandas é amplamente utilizada para trabalhar com Series. Para criar um Series em padas, você pode usar a função **Series()**, passando uma lista de elementos como argumentos:


In [3]:
import pandas as pd

s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


-  Nesse exemplo, a variável é uma Series com os elementos 1,2,3,4 e 5. A diferença etre uma **lista** e uma **Series** é que esta tem um índice associado a cada elemento, que pode ser usado para acessar os elementos individualmente.
- Você pode acessar os elementos da Series usando a notação de colchete como em **s[0]**, para acessar o primeiro elemento. Também é possivel acessar vários elemtnos de uma vez, como em **s[0:3]** para acessar os elementos de índice 0 a 2.
- Panda também oferece muitos funcionalidades para criar e manipular Series de forma eficiente. Por exemplo, você pode crir uma Series com valores sequenciais usando a funçãi **range()** e a função Series():



In [4]:
s = pd.Series(range(1,6))
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


Para criar uma Series com **rótulo personalizado**, você pode usar a função Series() e passar uma lista de rótumos como argumentos.

In [5]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


- Nesse exemplo, a Series tem rótulos personalizados para cada elemento: 'a' para 1, 'b' para 2, 'c' para 3, 'd' para 4 e 'e' para 5. Você pode acessar os elementos uando os rótulos, como em **s['a']**.

- Pandas também oferece muitas funções para manipular e processar Series, como **sum()**, **mean()**, **std()**, **max()** e **min()**. Essas funções permitem realizar operações matemáticas em Series e obter **estatisticas** sobre seus valores.
- Por exemplo: para calcular a média dos valores de uma Series você pode usar a função **mean()**, como em **s.mean()**. Para obter o valor máximo da Series, você pode usar a função **max()**, como em **s.max()**

In [6]:
s.max()

5

- Pandas também oferece muitas funcionalidades para operações de **agregação**, como agrupamento de dados, agregação de dados e resumos estatísticos
- Como vimos, essas são apenas algumas das funcionalidade oferecidas pelo Pandas para trabalhar com Series em Python. Vamos conferir agora os dataframes, estrutura semelhante, mas em duas dimenções.

# <font color = orange>DATAFRAMES

- Dataframes em Python são uma estrutura de dados bidimencional organizada em linha e colunas, semelhante a uma tabela de banco de dados ou a uma planilha do Excel. É uma das estruturas de dados mais utilizadas na análise e na manipulação de dados em Python.
- Existem várias bibliotecas em Python que oferecem suporte à criação e à manipulação de dataframes, mas a mais comun é a biclioteca Pandas.
- Para criar uma dataframa em Pandas, você pode usar a funções DataFrame(), que permite criar um dataframe a partir de **diferentes tipos de dados**, como listas, dicionarios e arquivos CSV.
- Por exemplo, para criar um dataframe a partir de uma lista de dicionarios, você pode usar o seguinte código:

In [10]:
import pandas as pd
dados = [
    {'nome': 'João', 'idade': 30, 'cidade':'São Paulo'},
    {'nome': 'Maria', 'idade': 25, 'cidade':'Rio de Janeiro'},
    {'nome': 'Pedro', 'idade': 40, 'cidade':'Belo horizonte'}

]
df = pd.DataFrame(dados)
df

nome  idade          cidade
0   João     30       São Paulo
1  Maria     25  Rio de Janeiro
2  Pedro     40  Belo horizonte

- Nesse exemplo, a lista dados contém trés dicionarios, cada um representando uma linha do daframe.

Voce pode acessar os coluna do dataframe usando a notação de colchetes, como em **df['idade']**. Você também pode usar a função **head()** para ver as primeiras linhas do dataframe:

In [11]:
print(df['nome'])
print(df.head())

0     João
1    Maria
2    Pedro
Name: nome, dtype: object
    nome  idade          cidade
0   João     30       São Paulo
1  Maria     25  Rio de Janeiro
2  Pedro     40  Belo horizonte


Além disso, o Pandas oferece muitas funções úteis para manipular dataframes, como **groupby()**, **merge()** e **pivot_table()**. Essas funções permitem agrupar dados, combinar dataframes e criar tabelas dinâmicas, respectivamente.

Por exemplo, você pode agrupar os dados por cidade e calcular a média da idade para cada cidade, usando o seguinte código:

In [17]:
df_por_didade = df.groupby('cidade').mean()
print(df_por_didade)

                idade
cidade               
Belo horizonte   40.0
Rio de Janeiro   25.0
São Paulo        30.0


<ipython-input-17-746ebce3b129>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_por_didade = df.groupby('cidade').mean()


Como vimos, essas são apenas alguma das funcionalidades oferecidas pelo Pandas para trabalhar com dataframe em Python. A biblioteca também oferece suporte a operações de seleção, filtragem, ordenação e agregação de dados, bem como leitura e gravação de arquivos CSV, Excel e outros formatos.

# <font color = orange>Para refletir

Qual é a principal diferença entre Series e Array em Python, e em que situação cada uma dessa estruturas de dados seriam mais útil em um projeto prático?

Em python, "Series" e "Arrays" geralmente se referem a diferenes estrutura de dados oferecidas por bibliotecas especificas, principalmente pandas e Numpy, respectivamente.

##1. **Series(pandas)**:
- Uma "Series" é uma estrutura de dados unidimencional fornecida pela bilbioteca padas.
- Ela é semelhante a uma coluna em uma planilha ou a um vetor em matemática.
- Pode conter dados de diferente tipos. mas é otimizada para dados de um tipo único.
- Oferece rótulo de índice para acessar os elementos.
- Podem se pensada como um colina em um DataFrame, uma estrutura de dados bidimensional do pandas.
- Útil para manipulação, análise e transformação de dados tabulares.

Quando usar Series(pandas):

- Quando você está trabalhando com dados tabulares, como carregar e manipular dados de arquivos CSV ou Excel.
- Para análise exploratória de dados, filtragem, agrupamento, ordenação e cálculos em calunas.
- Quando precisa associar rótulo e elementos em um vetor unidimensional.

##2. **Array(Numpy)**:
- Um "Array" é um estrutura de dados **multidimencional** fornecida pela biblioteca NumPy.
- É uma coleção homogênea de elementos, **normalmente do mesmo tipo**.
- Possui vantagem em termos de eficiência computacional e capacidade de realizar operações vetorizadas.
- É a base para muitas outras operações **numéricas** e cientificas em Python.
- **Não oferece rótulos** de indice como as "Series" do Pandas.

Quando usar Array(NumPy):
- Para cálculos numéricos intensivos, especialmente quadno você precisa realizar operalçoes em larga escala em dados multidimensionais.
- Processamento de imagens, sinais, modelagem matemática e estatístisca.
- Algoritimo que envolvem manipulação eficiênte de matrizes e vetores.

Em resumo, se você esta trabalhando prnicipalmente com análise de dados tabulares e precisa de funcionalidades de manipulação de dados mais avançadas, as "Series" do pandas são mais adequadas. Por outro lado, se esta focado em cálculos numéricos e operações em grande escala com matrizes vetores, os "Array" do Numpy são a escokha ideal. Muitas Vezes, essas duas estruturas de dados são usadas em conjunto para análise de dados complexa e eficiênte.